#配置

#应用服务器启动端口
server:
  port: 8080

spring:
  #jackson序列化时间格式转换,全局配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  application:
    name: WuXiang-Blog

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  #数据库配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      url: jdbc:mysql://106.13.195.2:3306/wuxiangblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: wuxiangblog
      password: wuxiangblog
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      filters: stat,wall

  #开启热修复
  devtools:
    restart:
      enabled: true


#netty配置

##分页插件配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

##mybatis配置
#mybatis:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#mybatisplus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.wuxianggujun.wuxiangblog.entity.**,com.wuxianggujun.wuxiangblog.entity.**
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" #逻辑未删除值(默认为 N)
      #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    cache-enabled: false
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info

        boot:
          autoconfigure: error


  file:
    name: blog/blog-dev.log


